version: "3.3"
services:
  frontend:
    build: ./frontend
    image: nghartey/todo-app-frontend:latest
    container_name: todo-app-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    build: ./backend
    image: nghartey/todo-app-backend:latest
    container_name: todo-app-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000
    
